# Objective: Manipulate arrays with ease and comprehend broadcasting to write operations without loops.

# NumPy Fundamentals

**NumPy** is a package for scientific computing with Python.

## Features

- **Powerful N-dimensional arrays** — allows vectorization, indexing, and broadcasting.
- **Numerical computing tools** — offers comprehensive mathematical functions, random number generators, linear algebra routines, and Fourier transforms.
- **Open source** — freely available and community-driven.
- **Interoperable** — compatible with many hardware and computing platforms.
- **Performant** — built on C code, which makes it optimized.
- **Easy to use** — its high-level syntax makes it accessible and productive.

In [1]:
"""
To try the examples in the browser:
1. Type code in the input cell and press
   Shift + Enter to execute
2. Or copy paste the code, and click on
   the "Run" button in the toolbar
"""

# The standard way to import NumPy:
import numpy as np

# Create a 2-D array, set every second element in
# some rows and find max per row:

x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x
# array([[  0,   1,   2,   3,   4],
#        [-99,   6, -99,   8, -99],
#        [-99,  11, -99,  13, -99]])

x.max(axis=1)
# array([ 4,  8, 13])

# Generate normally distributed random numbers:
rng = np.random.default_rng()
samples = rng.normal(size=2500)
samples

array([-0.42528144,  0.16502101,  0.83601142, ...,  2.16060131,
        1.00785339,  0.1189508 ])

In [ ]:
'''
ndarray (array):
Class to represent an "N-dimensional array"
Restrictions for NumPy Array:
-All elementos of the array must be of the same type of data
-Once created, the total size of the array cannot change
-The shape must be rectangular. Each row of a 2-dimensional
array must have the same number of columns
'''
#Initializing an array:
a = np.array([1, 2, 3, 4, 5, 6])
a
a[0]= 0
a[:3]

array([0, 2, 3])

In [ ]:
'''
Axes
Dimensions of an array
The column index corresponds to the last index, meanwhile, the row index is the second to last index
'''


#**Array Attributes**

In [ ]:
'''
There are 4 attributes of arrays
-ndim
-shape
-size
-dtype
'''
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#ndim: number of dimensions of an array
a.ndim

#shape: a tuple of non-negative integers that returns the number of elements along each dimension
a.shape
#size: it returns the total of elements in an array
a.size
#dtype: It returns the data type of the elements of the array.
#Numpy arrays only contains one type of data type at a time
a.dtype

dtype('int64')

#**How to create a basic array**

In [ ]:
#array of zeros
np.zeros(2)
#array of ones
np.ones(2)
#empty array
np.empty(2)
#array with a range of elements
np.arange(10)
#array that contains a range of evenly spaced intervals
np.arange(2, 9, 2) #np.arange(first number, last number, step size)
#array with uniformly distributed elements between 2 intervals
np.linspace(0, 15, num=6) #np.linspace(first number, last number, number of elements)
#specifying the data type
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

#**Adding, removing, and sorting elements**

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
#Sorting the previous array
np.sort(arr)
#Another methods to sort elements
#-argsort
#-legsort
#-searchsorted
#-partition

#Concatenate arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))


#Concatenating with an axis
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
z = np.concatenate((x, y), axis=0)
z.shape


a = np.array([[1, 2], [3, 4]])
b = np.array([[5],[ 6]])
c = np.concatenate((a, b), axis=1)
c


array([[1, 2, 5],
       [3, 4, 6]])

#**Broadcasting**

In [ ]:
#Level 1: Guessing the shape of arrays
A = np.array([1,2,3,4])

print(A.shape) #(4,)

A = np.array([[1,2,3],
              [4,5,6]])

print(A.shape)#(2,3)

A = np.array([[[1],[2],[3]]])

print(A.shape) #(,,1) Real: (1,3,1)

(4,)
(2, 3)
(1, 3, 1)


In [5]:
#Level 2: Basic Broadcasting
A = np.ones((3,4))
B = 5

A + B #It returns [[6,6,6,6],[6,6,6,6],[6,6,6,6]]

A = np.ones((3,4)) #shape = (3,4)
B = np.array([1,2,3,4]) #shape = (4,)

A + B #It returns [[2,3,4,5], [2,3,4,5],[2,3,4,5]]

A = np.ones((3,4)) #shape = (3,4)
B = np.array([[1,2,3,4]]) #shape = (1,4)

A + B #It returns [[2,3,4,5],[2,3,4,5],[2,3,4,5]]

A = np.ones((3,4)) #shape = (3,4)
B = np.array([[1], #shape = (3,1)
              [2],
              [3]])

A + B #It returns error: CORRECTED: It returns [[2,2,2,2], [3,3,3,3], [4,4,4,4]]


array([[2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [14]:
#Level 3: Broadcast or error?
#Tip:in shape = (a,b) Last number (b) corresponds to the column number, while the second to last number (a) corresponds to rows number
A = np.ones((5,4)) #shape = (5,4)
B = np.array([1,2,3]) #shape = (1,3) corrected: shape = (3,)

#A+B #It returns error: It fails at both dimensions


A = np.ones((2,3,4)) #shape = (2,3,4)
B = np.ones((3,4)) #shape = (3,4)

A+B #It returns error: it fails at first dimension 
'''
CORRECTED: It returns [[[2,2,2,2],
                        [2,2,2,2],
                        [2,2,2,2]],
                        
                        [[2,2,2,2],
                        [2,2,2,2],
                        [2,2,2,2]]]
'''
A = np.ones((2,3,4))
B = np.ones((2,4))

#A+B #It returns error: It fails at second dimension (rows)


A = np.ones((10,1,8))
B = np.ones((7,8))


'''
It returns:
[
[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

[[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2],
[2,2,2,2,2,2,2,2]],

]
'''
A+B 

array([[[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]],

       [[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.,

In [17]:
#Level 4: Keepdims:

A = np.random.rand(100,20)

print(A.mean(axis=0).shape) #shape = (,20) CORRECTED: shape = (20,)

print(A.mean(axis=1).shape) #shape = (100,)

print(A.mean(axis=1, keepdims=True).shape) #shape = (100,20) CORRECTED: shape = (100,1)



(20,)
(100,)
(100, 1)


In [23]:
#Level 5: np.newaxis

A = np.array([1,2,3])

print(A.shape) #shape = (3,)

print(A[:, np.newaxis].shape) #shape = (3,1)

print(A[np.newaxis, :].shape) #shape = (1,3)

A = np.array([1,2,3]) #shape = (3,)

print(A[:,None].shape) #shape = (3,1)

A = np.array([1,2,3]) #shape = (3,)

A[None,:] #np.array([1.,2.,3.]) CORRECTED [[1,2,3]]

(3,)
(3, 1)
(1, 3)
(3, 1)


array([[1, 2, 3]])

In [34]:
#Level 6: Advanced Broadcasting

A = np.arange(12).reshape(3,4)
'''
[
[0,1,2,3],
[4,5,6,7],
[8,9,10,11],
]
'''
row_mean = A.mean(axis=1, keepdims=True) #shape = (3,1)

'''
[
[1.5],
[5.5],
[9.5]
]
'''

print(A-row_mean)
'''
[
[-1.5,-0.5,0.5,1.5],
[-1.5,-0.5,0.5,1.5],
[-1.5,-0.5,0.5,1.5],
]
'''
# Pregunta: ¿Qué está haciendo matemáticamente? It is forming 4 Columns  with values that goes from -1.5 to 1.5 each 0.5


A = np.arange(12).reshape(3,4)
'''
[
[0,1,2,3],
[4,5,6,7],
[8,9,10,11],
]
'''
col_mean = A.mean(axis=0)
print(col_mean)
'''
[4,5,6,7] shape = (4,) 
'''
print(A-col_mean)#it returns error because column dimensions are not broadcastable 
#CORRECTED: It returns [ [-4,-4,-4,-4], [0,0,0,0], [4,4,4,4] ] 
#Pregunta: ¿Qué representa esta operación? It represents a standardization of values and how far are these from the mean of each column



#Obtain the difference matrix aming all the pairs of elements of the array of below witout using for
x = np.array([1,3,7,10])
xkeepdims= x[:, None]
ykeepdims= x[None, :]
z = xkeepdims-ykeepdims

z
print(xkeepdims)
print(ykeepdims)
print(z)
print(ykeepdims-xkeepdims)

[[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]
[4. 5. 6. 7.]
[[-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]
[[ 1]
 [ 3]
 [ 7]
 [10]]
[[ 1  3  7 10]]
[[ 0 -2 -6 -9]
 [ 2  0 -4 -7]
 [ 6  4  0 -3]
 [ 9  7  3  0]]
[[ 0  2  6  9]
 [-2  0  4  7]
 [-6 -4  0  3]
 [-9 -7 -3  0]]


In [ ]:
'''
Level 7: Interview
For each problem:
a) Is there broadcasting
b) What is the final shape

A = (4,5)
B = (5,)
a) Yes
b) (4,5)


A = (4,5)
B = (4,)
a) No
b) Error

A = (1,7,1)
B = (5,1,8)
a) Yes
b) (5,7,8)


A = (3,1,5,1)
B = (1,4,1)
a) No
b) Error

A = (8,1,6,1)
B = (7,1,5)
a) Yes
b) (8,7,6,5)
'''




